version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
    timezone: Pacific/Auckland
  open-pull-requests-limit: 100
  
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: APacific/Auckland
  open-pull-requests-limit: 100
  reviewers:
  - johnnyfleet
  assignees:
  - johnnyfleet

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Pacific/Auckland
  open-pull-requests-limit: 100
  reviewers:
  - johnnyfleet
  assignees:
  - johnnyfleeto
